Exception ignored in: <bound method MinionSol.__del__ of <minion.MinionSol object at 0x2b54c4189fd0>>
Traceback (most recent call last):
  File "/home/pventura/relationaldef/minion.py", line 132, in __del__
    def __del__(self):
KeyboardInterrupt
Spectrum = [3, 2, 1]
DEFINABLE

Final state: 
  Diversity = 10006
    1-diversity = 2
    2-diversity = 126
    3-diversity = 9878
  #Auts = 17
  #Isos = 693
  5344769 calls to Minion

 Performance counter stats for 'timeout --signal=SIGINT 45m python3 ../../relationaldef/main.py':

   16664484.115956      task-clock (msec)         #    1.066 CPUs utilized          
        24,095,849      context-switches          #    0.001 M/sec                  
         1,741,711      cpu-migrations            #    0.105 K/sec                  
     2,508,055,303      page-faults               #    0.151 M/sec                  
43,454,129,950,997      cycles                    #    2.608 GHz                    
32,148,168,183,342      instructions              #    0.74  insn per cycle         
 6,527,793,836,557      branches                  #  391.719 M/sec                  
   123,984,241,306      branch-misses             #    1.90% of all branches        

   15639.552908784 seconds time elapsed

