Exception ignored in: <bound method MinionSol.__del__ of <minion.MinionSol object at 0x2b7bc76757b8>>
Traceback (most recent call last):
  File "/home/pventura/relationaldef/minion.py", line 136, in __del__
    if not self.EOF:
AttributeError: 'MinionSol' object has no attribute 'EOF'
Spectrum = [3, 2, 1]
CANCELLED

State before abort: 
  Diversity = 2429
    1-diversity = 2
    2-diversity = 44
    3-diversity = 2383
  #Auts = 50
  #Isos = 5581
  1136052 calls to Minion
